from .mrrparse import *

DATA = {
    "parser": {
        "lexer_conf": {
            "terminals": [
                {"@": 0},
                {"@": 1},
                {"@": 2},
                {"@": 3},
                {"@": 4},
                {"@": 5},
                {"@": 6},
                {"@": 7},
                {"@": 8},
                {"@": 9},
                {"@": 10},
                {"@": 11},
                {"@": 12},
                {"@": 13},
                {"@": 14},
                {"@": 15},
                {"@": 16},
                {"@": 17},
                {"@": 18},
                {"@": 19},
                {"@": 20},
                {"@": 21},
                {"@": 22},
                {"@": 23},
                {"@": 24},
                {"@": 25},
                {"@": 26},
                {"@": 27},
                {"@": 28},
                {"@": 29},
                {"@": 30},
                {"@": 31},
            ],
            "ignore": ["WS_INLINE"],
            "g_regex_flags": 0,
            "use_bytes": False,
            "lexer_type": "contextual",
            "__type__": "LexerConf",
        },
        "parser_conf": {
            "rules": [
                {"@": 32},
                {"@": 33},
                {"@": 34},
                {"@": 35},
                {"@": 36},
                {"@": 37},
                {"@": 38},
                {"@": 39},
                {"@": 40},
                {"@": 41},
                {"@": 42},
                {"@": 43},
                {"@": 44},
                {"@": 45},
                {"@": 46},
                {"@": 47},
                {"@": 48},
                {"@": 49},
                {"@": 50},
                {"@": 51},
                {"@": 52},
                {"@": 53},
                {"@": 54},
                {"@": 55},
                {"@": 56},
                {"@": 57},
                {"@": 58},
                {"@": 59},
                {"@": 60},
                {"@": 61},
                {"@": 62},
                {"@": 63},
                {"@": 64},
                {"@": 65},
                {"@": 66},
                {"@": 67},
                {"@": 68},
                {"@": 69},
                {"@": 70},
                {"@": 71},
                {"@": 72},
                {"@": 73},
                {"@": 74},
                {"@": 75},
                {"@": 76},
                {"@": 77},
                {"@": 78},
                {"@": 79},
                {"@": 80},
                {"@": 81},
                {"@": 82},
                {"@": 83},
                {"@": 84},
                {"@": 85},
                {"@": 86},
                {"@": 87},
                {"@": 88},
                {"@": 89},
                {"@": 90},
                {"@": 91},
                {"@": 92},
                {"@": 93},
                {"@": 94},
                {"@": 95},
                {"@": 96},
                {"@": 97},
                {"@": 98},
                {"@": 99},
                {"@": 100},
                {"@": 101},
                {"@": 102},
                {"@": 103},
                {"@": 104},
                {"@": 105},
                {"@": 106},
                {"@": 107},
                {"@": 108},
                {"@": 109},
                {"@": 110},
                {"@": 111},
                {"@": 112},
                {"@": 113},
                {"@": 114},
                {"@": 115},
                {"@": 116},
                {"@": 117},
                {"@": 118},
                {"@": 119},
                {"@": 120},
                {"@": 121},
                {"@": 122},
                {"@": 123},
                {"@": 124},
                {"@": 125},
                {"@": 126},
                {"@": 127},
                {"@": 128},
                {"@": 129},
                {"@": 130},
            ],
            "start": ["start"],
            "parser_type": "lalr",
            "__type__": "ParserConf",
        },
        "parser": {
            "tokens": {
                0: "UNOP",
                1: "__ANON_1",
                2: "_NL",
                3: "COMMA",
                4: "FOR",
                5: "ASSIGN",
                6: "CMP",
                7: "RSQB",
                8: "NAME",
                9: "__constraints_plus_3",
                10: "LSQB",
                11: "INT",
                12: "start",
                13: "condition",
                14: "actdecl",
                15: "var",
                16: "__start_star_10",
                17: "quantifier",
                18: "assignment",
                19: "$END",
                20: "AT",
                21: "BINOP",
                22: "__actdecl_star_7",
                23: "atloc",
                24: "__quantifier_star_9",
                25: "__quantifier_star_8",
                26: "STAR",
                27: "QUANTI",
                28: "__actdecl_star_6",
                29: "index",
                30: "NAT",
                31: "TAGS",
            },
            "states": {
                0: {},
                1: {
                    0: (1, {"@": 98}),
                    1: (1, {"@": 98}),
                    2: (1, {"@": 98}),
                    3: (1, {"@": 98}),
                    4: (1, {"@": 98}),
                    5: (1, {"@": 98}),
                    6: (1, {"@": 98}),
                },
                2: {7: (1, {"@": 100})},
                3: {
                    8: (0, 98),
                    9: (0, 102),
                    10: (0, 101),
                    11: (0, 59),
                    12: (0, 0),
                    13: (0, 90),
                    14: (0, 32),
                    15: (0, 31),
                    2: (0, 49),
                    16: (0, 27),
                },
                4: {4: (0, 56), 3: (0, 5), 17: (0, 29), 2: (0, 34)},
                5: {8: (0, 98), 15: (0, 83), 18: (0, 44)},
                6: {
                    8: (1, {"@": 130}),
                    2: (1, {"@": 130}),
                    10: (1, {"@": 130}),
                    11: (1, {"@": 130}),
                    19: (1, {"@": 130}),
                },
                7: {7: (0, 8)},
                8: {8: (0, 98), 15: (0, 31), 11: (0, 59), 13: (0, 61)},
                9: {8: (0, 98), 11: (0, 81), 15: (0, 47)},
                10: {
                    20: (0, 100),
                    0: (1, {"@": 94}),
                    6: (1, {"@": 94}),
                    5: (1, {"@": 94}),
                    1: (1, {"@": 94}),
                    3: (1, {"@": 94}),
                    4: (1, {"@": 94}),
                    2: (1, {"@": 94}),
                },
                11: {
                    8: (1, {"@": 74}),
                    19: (1, {"@": 74}),
                    11: (1, {"@": 74}),
                    2: (1, {"@": 74}),
                    10: (1, {"@": 74}),
                },
                12: {21: (0, 106), 7: (1, {"@": 102})},
                13: {
                    8: (1, {"@": 116}),
                    19: (1, {"@": 116}),
                    11: (1, {"@": 116}),
                    2: (1, {"@": 116}),
                    10: (1, {"@": 116}),
                },
                14: {2: (0, 6), 19: (1, {"@": 109})},
                15: {2: (0, 25)},
                16: {
                    8: (1, {"@": 81}),
                    19: (1, {"@": 81}),
                    11: (1, {"@": 81}),
                    2: (1, {"@": 81}),
                    10: (1, {"@": 81}),
                },
                17: {2: (0, 6), 19: (1, {"@": 107})},
                18: {4: (1, {"@": 89}), 2: (1, {"@": 89}), 3: (1, {"@": 89})},
                19: {1: (1, {"@": 88}), 3: (1, {"@": 88})},
                20: {4: (1, {"@": 90}), 2: (1, {"@": 90}), 3: (1, {"@": 90})},
                21: {8: (0, 98), 18: (0, 70), 15: (0, 83)},
                22: {4: (1, {"@": 91}), 2: (1, {"@": 91}), 3: (1, {"@": 91})},
                23: {1: (0, 36), 3: (0, 88)},
                24: {
                    8: (1, {"@": 78}),
                    19: (1, {"@": 78}),
                    11: (1, {"@": 78}),
                    2: (1, {"@": 78}),
                    10: (1, {"@": 78}),
                },
                25: {
                    8: (1, {"@": 80}),
                    19: (1, {"@": 80}),
                    11: (1, {"@": 80}),
                    2: (1, {"@": 80}),
                    10: (1, {"@": 80}),
                },
                26: {8: (0, 98), 15: (0, 83), 18: (0, 48)},
                27: {
                    8: (0, 98),
                    9: (0, 82),
                    10: (0, 101),
                    11: (0, 59),
                    13: (0, 90),
                    14: (0, 32),
                    15: (0, 31),
                    2: (0, 6),
                },
                28: {8: (0, 98), 15: (0, 31), 11: (0, 59), 13: (0, 105)},
                29: {2: (0, 54)},
                30: {4: (0, 56), 3: (0, 76), 22: (0, 46), 2: (0, 60), 17: (0, 62)},
                31: {0: (0, 19), 6: (0, 66)},
                32: {
                    8: (1, {"@": 115}),
                    19: (1, {"@": 115}),
                    11: (1, {"@": 115}),
                    2: (1, {"@": 115}),
                    10: (1, {"@": 115}),
                },
                33: {20: (0, 71), 23: (0, 55), 8: (0, 78)},
                34: {
                    8: (1, {"@": 77}),
                    19: (1, {"@": 77}),
                    11: (1, {"@": 77}),
                    2: (1, {"@": 77}),
                    10: (1, {"@": 77}),
                },
                35: {24: (0, 65), 25: (0, 67), 3: (0, 69), 2: (1, {"@": 106})},
                36: {8: (0, 98), 15: (0, 83), 18: (0, 39)},
                37: {1: (0, 26), 3: (0, 88)},
                38: {1: (1, {"@": 85}), 3: (1, {"@": 85})},
                39: {4: (0, 56), 3: (0, 76), 22: (0, 4), 2: (0, 64), 17: (0, 68)},
                40: {
                    8: (1, {"@": 72}),
                    19: (1, {"@": 72}),
                    11: (1, {"@": 72}),
                    2: (1, {"@": 72}),
                    10: (1, {"@": 72}),
                },
                41: {4: (0, 56), 2: (0, 89), 3: (0, 5), 17: (0, 91)},
                42: {4: (0, 56), 17: (0, 95)},
                43: {8: (0, 98), 15: (0, 18), 11: (0, 20), 26: (0, 22)},
                44: {4: (1, {"@": 124}), 2: (1, {"@": 124}), 3: (1, {"@": 124})},
                45: {1: (1, {"@": 122}), 3: (1, {"@": 122})},
                46: {4: (0, 56), 17: (0, 52), 3: (0, 5), 2: (0, 73)},
                47: {1: (1, {"@": 86}), 3: (1, {"@": 86})},
                48: {4: (0, 56), 17: (0, 63), 22: (0, 41), 3: (0, 76), 2: (0, 72)},
                49: {
                    8: (1, {"@": 129}),
                    2: (1, {"@": 129}),
                    10: (1, {"@": 129}),
                    11: (1, {"@": 129}),
                    19: (1, {"@": 129}),
                },
                50: {4: (1, {"@": 123}), 2: (1, {"@": 123}), 3: (1, {"@": 123})},
                51: {4: (1, {"@": 92}), 2: (1, {"@": 92}), 3: (1, {"@": 92})},
                52: {2: (0, 40)},
                53: {4: (0, 56), 3: (0, 5), 17: (0, 15), 2: (0, 16)},
                54: {
                    8: (1, {"@": 76}),
                    19: (1, {"@": 76}),
                    11: (1, {"@": 76}),
                    2: (1, {"@": 76}),
                    10: (1, {"@": 76}),
                },
                55: {
                    0: (1, {"@": 95}),
                    6: (1, {"@": 95}),
                    5: (1, {"@": 95}),
                    1: (1, {"@": 95}),
                    3: (1, {"@": 95}),
                    4: (1, {"@": 95}),
                    2: (1, {"@": 95}),
                },
                56: {27: (0, 103)},
                57: {2: (0, 92)},
                58: {1: (1, {"@": 84}), 3: (1, {"@": 84})},
                59: {6: (0, 9)},
                60: {
                    8: (1, {"@": 75}),
                    19: (1, {"@": 75}),
                    11: (1, {"@": 75}),
                    2: (1, {"@": 75}),
                    10: (1, {"@": 75}),
                },
                61: {28: (0, 37), 1: (0, 84), 3: (0, 28)},
                62: {2: (0, 11)},
                63: {2: (0, 74)},
                64: {
                    8: (1, {"@": 79}),
                    19: (1, {"@": 79}),
                    11: (1, {"@": 79}),
                    2: (1, {"@": 79}),
                    10: (1, {"@": 79}),
                },
                65: {3: (0, 42), 2: (1, {"@": 105})},
                66: {8: (0, 98), 11: (0, 38), 15: (0, 58)},
                67: {24: (0, 79), 3: (0, 80), 2: (1, {"@": 104})},
                68: {2: (0, 24)},
                69: {4: (0, 56), 17: (0, 77), 8: (0, 85)},
                70: {4: (0, 56), 17: (0, 57), 3: (0, 76), 22: (0, 53), 2: (0, 94)},
                71: {
                    0: (1, {"@": 97}),
                    1: (1, {"@": 97}),
                    2: (1, {"@": 97}),
                    3: (1, {"@": 97}),
                    4: (1, {"@": 97}),
                    5: (1, {"@": 97}),
                    6: (1, {"@": 97}),
                },
                72: {
                    8: (1, {"@": 71}),
                    19: (1, {"@": 71}),
                    11: (1, {"@": 71}),
                    2: (1, {"@": 71}),
                    10: (1, {"@": 71}),
                },
                73: {
                    8: (1, {"@": 73}),
                    19: (1, {"@": 73}),
                    11: (1, {"@": 73}),
                    2: (1, {"@": 73}),
                    10: (1, {"@": 73}),
                },
                74: {
                    8: (1, {"@": 70}),
                    19: (1, {"@": 70}),
                    11: (1, {"@": 70}),
                    2: (1, {"@": 70}),
                    10: (1, {"@": 70}),
                },
                75: {
                    0: (1, {"@": 93}),
                    6: (1, {"@": 93}),
                    5: (1, {"@": 93}),
                    1: (1, {"@": 93}),
                    3: (1, {"@": 93}),
                    4: (1, {"@": 93}),
                    2: (1, {"@": 93}),
                },
                76: {8: (0, 98), 15: (0, 83), 18: (0, 50)},
                77: {2: (1, {"@": 127}), 3: (1, {"@": 127})},
                78: {
                    10: (0, 93),
                    0: (1, {"@": 99}),
                    1: (1, {"@": 99}),
                    2: (1, {"@": 99}),
                    3: (1, {"@": 99}),
                    4: (1, {"@": 99}),
                    5: (1, {"@": 99}),
                    6: (1, {"@": 99}),
                },
                79: {3: (0, 42), 2: (1, {"@": 103})},
                80: {4: (0, 56), 17: (0, 77), 8: (0, 96)},
                81: {1: (1, {"@": 87}), 3: (1, {"@": 87})},
                82: {
                    8: (0, 98),
                    10: (0, 101),
                    11: (0, 59),
                    16: (0, 17),
                    13: (0, 90),
                    15: (0, 31),
                    2: (0, 49),
                    14: (0, 13),
                    19: (1, {"@": 108}),
                },
                83: {0: (0, 51), 5: (0, 43)},
                84: {8: (0, 98), 18: (0, 30), 15: (0, 83)},
                85: {2: (1, {"@": 125}), 3: (1, {"@": 125})},
                86: {7: (0, 10)},
                87: {
                    8: (1, {"@": 68}),
                    19: (1, {"@": 68}),
                    11: (1, {"@": 68}),
                    2: (1, {"@": 68}),
                    10: (1, {"@": 68}),
                },
                88: {8: (0, 98), 15: (0, 31), 11: (0, 59), 13: (0, 45)},
                89: {
                    8: (1, {"@": 69}),
                    19: (1, {"@": 69}),
                    11: (1, {"@": 69}),
                    2: (1, {"@": 69}),
                    10: (1, {"@": 69}),
                },
                90: {28: (0, 23), 1: (0, 21), 3: (0, 28)},
                91: {2: (0, 87)},
                92: {
                    8: (1, {"@": 82}),
                    19: (1, {"@": 82}),
                    11: (1, {"@": 82}),
                    2: (1, {"@": 82}),
                    10: (1, {"@": 82}),
                },
                93: {8: (0, 12), 29: (0, 104), 30: (0, 2)},
                94: {
                    8: (1, {"@": 83}),
                    19: (1, {"@": 83}),
                    11: (1, {"@": 83}),
                    2: (1, {"@": 83}),
                    10: (1, {"@": 83}),
                },
                95: {2: (1, {"@": 128}), 3: (1, {"@": 128})},
                96: {2: (1, {"@": 126}), 3: (1, {"@": 126})},
                97: {7: (1, {"@": 101})},
                98: {
                    10: (0, 99),
                    20: (0, 33),
                    0: (1, {"@": 96}),
                    6: (1, {"@": 96}),
                    5: (1, {"@": 96}),
                    1: (1, {"@": 96}),
                    3: (1, {"@": 96}),
                    4: (1, {"@": 96}),
                    2: (1, {"@": 96}),
                },
                99: {29: (0, 86), 8: (0, 12), 30: (0, 2)},
                100: {20: (0, 71), 8: (0, 78), 23: (0, 75)},
                101: {31: (0, 7)},
                102: {
                    8: (0, 98),
                    10: (0, 101),
                    11: (0, 59),
                    13: (0, 90),
                    16: (0, 14),
                    15: (0, 31),
                    2: (0, 49),
                    14: (0, 13),
                    19: (1, {"@": 110}),
                },
                103: {8: (0, 35)},
                104: {7: (0, 1)},
                105: {1: (1, {"@": 121}), 3: (1, {"@": 121})},
                106: {30: (0, 97)},
            },
            "start_states": {"start": 3},
            "end_states": {"start": 0},
        },
        "__type__": "ParsingFrontend",
    },
    "rules": [
        {"@": 32},
        {"@": 33},
        {"@": 34},
        {"@": 35},
        {"@": 36},
        {"@": 37},
        {"@": 38},
        {"@": 39},
        {"@": 40},
        {"@": 41},
        {"@": 42},
        {"@": 43},
        {"@": 44},
        {"@": 45},
        {"@": 46},
        {"@": 47},
        {"@": 48},
        {"@": 49},
        {"@": 50},
        {"@": 51},
        {"@": 52},
        {"@": 53},
        {"@": 54},
        {"@": 55},
        {"@": 56},
        {"@": 57},
        {"@": 58},
        {"@": 59},
        {"@": 60},
        {"@": 61},
        {"@": 62},
        {"@": 63},
        {"@": 64},
        {"@": 65},
        {"@": 66},
        {"@": 67},
        {"@": 68},
        {"@": 69},
        {"@": 70},
        {"@": 71},
        {"@": 72},
        {"@": 73},
        {"@": 74},
        {"@": 75},
        {"@": 76},
        {"@": 77},
        {"@": 78},
        {"@": 79},
        {"@": 80},
        {"@": 81},
        {"@": 82},
        {"@": 83},
        {"@": 84},
        {"@": 85},
        {"@": 86},
        {"@": 87},
        {"@": 88},
        {"@": 89},
        {"@": 90},
        {"@": 91},
        {"@": 92},
        {"@": 93},
        {"@": 94},
        {"@": 95},
        {"@": 96},
        {"@": 97},
        {"@": 98},
        {"@": 99},
        {"@": 100},
        {"@": 101},
        {"@": 102},
        {"@": 103},
        {"@": 104},
        {"@": 105},
        {"@": 106},
        {"@": 107},
        {"@": 108},
        {"@": 109},
        {"@": 110},
        {"@": 111},
        {"@": 112},
        {"@": 113},
        {"@": 114},
        {"@": 115},
        {"@": 116},
        {"@": 117},
        {"@": 118},
        {"@": 119},
        {"@": 120},
        {"@": 121},
        {"@": 122},
        {"@": 123},
        {"@": 124},
        {"@": 125},
        {"@": 126},
        {"@": 127},
        {"@": 128},
        {"@": 129},
        {"@": 130},
    ],
    "options": {
        "debug": False,
        "strict": False,
        "keep_all_tokens": False,
        "tree_class": None,
        "cache": False,
        "postlex": None,
        "parser": "lalr",
        "lexer": "contextual",
        "transformer": None,
        "start": ["start"],
        "priority": "normal",
        "ambiguity": "auto",
        "regex": False,
        "propagate_positions": False,
        "lexer_callbacks": {},
        "maybe_placeholders": False,
        "edit_terminals": None,
        "g_regex_flags": 0,
        "use_bytes": False,
        "ordered_sets": True,
        "import_paths": [],
        "source_path": None,
        "_plugins": {},
    },
    "__type__": "Lark",
}
MEMO = {
    0: {
        "name": "WS_INLINE",
        "pattern": {
            "value": "(?:(?:\\ |\t))+",
            "flags": [],
            "raw": None,
            "_width": [1, 18446744073709551616],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    1: {
        "name": "QUANTI",
        "pattern": {
            "value": "all|any",
            "flags": [],
            "raw": "/all|any/",
            "_width": [3, 3],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    2: {
        "name": "NAME",
        "pattern": {
            "value": "[a-z][a-z0-9]*",
            "flags": ["i"],
            "raw": "/[a-z][a-z0-9]*/i",
            "_width": [1, 18446744073709551616],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    3: {
        "name": "NAT",
        "pattern": {
            "value": "[0-9]+",
            "flags": [],
            "raw": "/[0-9]+/",
            "_width": [1, 18446744073709551616],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    4: {
        "name": "INT",
        "pattern": {
            "value": "[+-]?[0-9]+",
            "flags": [],
            "raw": "/[+-]?[0-9]+/",
            "_width": [1, 18446744073709551616],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    5: {
        "name": "CMP",
        "pattern": {
            "value": "(?:==|<=|>=|!=|<|>)",
            "flags": [],
            "raw": None,
            "_width": [1, 2],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    6: {
        "name": "ASSIGN",
        "pattern": {
            "value": "[+-]?=",
            "flags": [],
            "raw": "/[+-]?=/",
            "_width": [1, 2],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    7: {
        "name": "UNOP",
        "pattern": {
            "value": "(?:\\+\\+|\\-\\-|\\+|\\-|\\*|\\~)",
            "flags": [],
            "raw": None,
            "_width": [1, 2],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    8: {
        "name": "BINOP",
        "pattern": {
            "value": "(?:\\+|\\-)",
            "flags": [],
            "raw": None,
            "_width": [1, 1],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    9: {
        "name": "AT",
        "pattern": {"value": "@", "flags": [], "raw": '"@"', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    10: {
        "name": "TAGS",
        "pattern": {
            "value": "[^\\]\n\r]+",
            "flags": [],
            "raw": "/[^\\]\\n\\r]+/",
            "_width": [1, 18446744073709551616],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    11: {
        "name": "DESC",
        "pattern": {
            "value": "[^\n\r]+",
            "flags": [],
            "raw": "/[^\\n\\r]+/",
            "_width": [1, 18446744073709551616],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    12: {
        "name": "_NL",
        "pattern": {
            "value": "(\r?\n[\t ]*)+",
            "flags": [],
            "raw": "/(\\r?\\n[\\t ]*)+/",
            "_width": [1, 18446744073709551616],
            "__type__": "PatternRE",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    13: {
        "name": "COLON",
        "pattern": {"value": ":", "flags": [], "raw": '":"', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    14: {
        "name": "VARIABLES",
        "pattern": {
            "value": "variables",
            "flags": [],
            "raw": '"variables"',
            "__type__": "PatternStr",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    15: {
        "name": "CONSTRAINTS",
        "pattern": {
            "value": "constraints",
            "flags": [],
            "raw": '"constraints"',
            "__type__": "PatternStr",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    16: {
        "name": "RULES",
        "pattern": {
            "value": "rules",
            "flags": [],
            "raw": '"rules"',
            "__type__": "PatternStr",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    17: {
        "name": "LSQB",
        "pattern": {"value": "[", "flags": [], "raw": '"["', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    18: {
        "name": "RSQB",
        "pattern": {"value": "]", "flags": [], "raw": '"]"', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    19: {
        "name": "LOCATION",
        "pattern": {
            "value": "location",
            "flags": [],
            "raw": '"location"',
            "__type__": "PatternStr",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    20: {
        "name": "EQUAL",
        "pattern": {"value": "=", "flags": [], "raw": '"="', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    21: {
        "name": "BOOL",
        "pattern": {
            "value": "bool",
            "flags": [],
            "raw": '"bool"',
            "__type__": "PatternStr",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    22: {
        "name": "LBRACE",
        "pattern": {"value": "{", "flags": [], "raw": '"{"', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    23: {
        "name": "__ANON_0",
        "pattern": {
            "value": "..",
            "flags": [],
            "raw": '".."',
            "__type__": "PatternStr",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    24: {
        "name": "RBRACE",
        "pattern": {"value": "}", "flags": [], "raw": '"}"', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    25: {
        "name": "COMMA",
        "pattern": {"value": ",", "flags": [], "raw": '","', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    26: {
        "name": "LPAR",
        "pattern": {"value": "(", "flags": [], "raw": '"("', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    27: {
        "name": "RPAR",
        "pattern": {"value": ")", "flags": [], "raw": '")"', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    28: {
        "name": "VBAR",
        "pattern": {"value": "|", "flags": [], "raw": '"|"', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    29: {
        "name": "STAR",
        "pattern": {"value": "*", "flags": [], "raw": '"*"', "__type__": "PatternStr"},
        "priority": 0,
        "__type__": "TerminalDef",
    },
    30: {
        "name": "__ANON_1",
        "pattern": {
            "value": ">>",
            "flags": [],
            "raw": '">>"',
            "__type__": "PatternStr",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    31: {
        "name": "FOR",
        "pattern": {
            "value": "for",
            "flags": [],
            "raw": '"for"',
            "__type__": "PatternStr",
        },
        "priority": 0,
        "__type__": "TerminalDef",
    },
    32: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "variables", "__type__": "NonTerminal"},
            {"name": "__model_star_1", "__type__": "NonTerminal"},
            {"name": "constraints", "__type__": "NonTerminal"},
            {"name": "rules", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    33: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "variables", "__type__": "NonTerminal"},
            {"name": "__model_star_1", "__type__": "NonTerminal"},
            {"name": "constraints", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, False, False, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    34: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "variables", "__type__": "NonTerminal"},
            {"name": "__model_star_1", "__type__": "NonTerminal"},
            {"name": "rules", "__type__": "NonTerminal"},
        ],
        "order": 2,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    35: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "variables", "__type__": "NonTerminal"},
            {"name": "__model_star_1", "__type__": "NonTerminal"},
        ],
        "order": 3,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, False, True, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    36: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "variables", "__type__": "NonTerminal"},
            {"name": "constraints", "__type__": "NonTerminal"},
            {"name": "rules", "__type__": "NonTerminal"},
        ],
        "order": 4,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    37: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "variables", "__type__": "NonTerminal"},
            {"name": "constraints", "__type__": "NonTerminal"},
        ],
        "order": 5,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, False, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    38: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "variables", "__type__": "NonTerminal"},
            {"name": "rules", "__type__": "NonTerminal"},
        ],
        "order": 6,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    39: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [{"name": "variables", "__type__": "NonTerminal"}],
        "order": 7,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    40: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__model_star_1", "__type__": "NonTerminal"},
            {"name": "constraints", "__type__": "NonTerminal"},
            {"name": "rules", "__type__": "NonTerminal"},
        ],
        "order": 8,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    41: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__model_star_1", "__type__": "NonTerminal"},
            {"name": "constraints", "__type__": "NonTerminal"},
        ],
        "order": 9,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    42: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__model_star_1", "__type__": "NonTerminal"},
            {"name": "rules", "__type__": "NonTerminal"},
        ],
        "order": 10,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    43: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [{"name": "__model_star_1", "__type__": "NonTerminal"}],
        "order": 11,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, True, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    44: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "constraints", "__type__": "NonTerminal"},
            {"name": "rules", "__type__": "NonTerminal"},
        ],
        "order": 12,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    45: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [{"name": "constraints", "__type__": "NonTerminal"}],
        "order": 13,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    46: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [{"name": "rules", "__type__": "NonTerminal"}],
        "order": 14,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    47: {
        "origin": {"name": Token("RULE", "model"), "__type__": "NonTerminal"},
        "expansion": [],
        "order": 15,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, True, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    48: {
        "origin": {"name": Token("RULE", "variables"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "VARIABLES", "filter_out": True, "__type__": "Terminal"},
            {"name": "COLON", "filter_out": True, "__type__": "Terminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
            {"name": "_INDENT", "filter_out": True, "__type__": "Terminal"},
            {"name": "__variables_plus_2", "__type__": "NonTerminal"},
            {"name": "_DEDENT", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    49: {
        "origin": {"name": Token("RULE", "constraints"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "CONSTRAINTS", "filter_out": True, "__type__": "Terminal"},
            {"name": "COLON", "filter_out": True, "__type__": "Terminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
            {"name": "_INDENT", "filter_out": True, "__type__": "Terminal"},
            {"name": "__constraints_plus_3", "__type__": "NonTerminal"},
            {"name": "_DEDENT", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    50: {
        "origin": {"name": Token("RULE", "rules"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "RULES", "filter_out": True, "__type__": "Terminal"},
            {"name": "COLON", "filter_out": True, "__type__": "Terminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
            {"name": "_INDENT", "filter_out": True, "__type__": "Terminal"},
            {"name": "__constraints_plus_3", "__type__": "NonTerminal"},
            {"name": "_DEDENT", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    51: {
        "origin": {"name": Token("RULE", "location"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LOCATION", "filter_out": True, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "NAT", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "COLON", "filter_out": True, "__type__": "Terminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
            {"name": "_INDENT", "filter_out": True, "__type__": "Terminal"},
            {"name": "model", "__type__": "NonTerminal"},
            {"name": "_DEDENT", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    52: {
        "origin": {"name": Token("RULE", "location"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LOCATION", "filter_out": True, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "COLON", "filter_out": True, "__type__": "Terminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
            {"name": "_INDENT", "filter_out": True, "__type__": "Terminal"},
            {"name": "model", "__type__": "NonTerminal"},
            {"name": "_DEDENT", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, False, True, False, False, False, False, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    53: {
        "origin": {"name": Token("RULE", "vardecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "type", "__type__": "NonTerminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "EQUAL", "filter_out": True, "__type__": "Terminal"},
            {"name": "init", "__type__": "NonTerminal"},
            {"name": "COLON", "filter_out": True, "__type__": "Terminal"},
            {"name": "DESC", "filter_out": False, "__type__": "Terminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 0,
        "alias": "vardecl_long",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    54: {
        "origin": {"name": Token("RULE", "vardecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "UNOP", "filter_out": False, "__type__": "Terminal"},
            {"name": "COLON", "filter_out": True, "__type__": "Terminal"},
            {"name": "DESC", "filter_out": False, "__type__": "Terminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": "vardecl_short",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    55: {
        "origin": {"name": Token("RULE", "type"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "simple_type", "__type__": "NonTerminal"},
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "NAT", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    56: {
        "origin": {"name": Token("RULE", "type"), "__type__": "NonTerminal"},
        "expansion": [{"name": "simple_type", "__type__": "NonTerminal"}],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    57: {
        "origin": {"name": Token("RULE", "simple_type"), "__type__": "NonTerminal"},
        "expansion": [{"name": "BOOL", "filter_out": True, "__type__": "Terminal"}],
        "order": 0,
        "alias": "type_bool",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    58: {
        "origin": {"name": Token("RULE", "simple_type"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LBRACE", "filter_out": True, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "COLON", "filter_out": True, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "__ANON_0", "filter_out": True, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "RBRACE", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": "type_clock",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    59: {
        "origin": {"name": Token("RULE", "simple_type"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LBRACE", "filter_out": True, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "__ANON_0", "filter_out": True, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "RBRACE", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 2,
        "alias": "type_interval",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    60: {
        "origin": {"name": Token("RULE", "init"), "__type__": "NonTerminal"},
        "expansion": [{"name": "simple_init", "__type__": "NonTerminal"}],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    61: {
        "origin": {"name": Token("RULE", "init"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LPAR", "filter_out": True, "__type__": "Terminal"},
            {"name": "simple_init", "__type__": "NonTerminal"},
            {"name": "__init_star_4", "__type__": "NonTerminal"},
            {"name": "RPAR", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": "init_seq",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    62: {
        "origin": {"name": Token("RULE", "init"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LPAR", "filter_out": True, "__type__": "Terminal"},
            {"name": "simple_init", "__type__": "NonTerminal"},
            {"name": "RPAR", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 2,
        "alias": "init_seq",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    63: {
        "origin": {"name": Token("RULE", "simple_init"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "__ANON_0", "filter_out": True, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "__simple_init_star_5", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": "init_int",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    64: {
        "origin": {"name": Token("RULE", "simple_init"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "__ANON_0", "filter_out": True, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": "init_int",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    65: {
        "origin": {"name": Token("RULE", "simple_init"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "__simple_init_star_5", "__type__": "NonTerminal"},
        ],
        "order": 2,
        "alias": "init_int",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    66: {
        "origin": {"name": Token("RULE", "simple_init"), "__type__": "NonTerminal"},
        "expansion": [{"name": "INT", "filter_out": False, "__type__": "Terminal"}],
        "order": 3,
        "alias": "init_int",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    67: {
        "origin": {"name": Token("RULE", "simple_init"), "__type__": "NonTerminal"},
        "expansion": [{"name": "STAR", "filter_out": True, "__type__": "Terminal"}],
        "order": 4,
        "alias": "init_all",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    68: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "TAGS", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    69: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "TAGS", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                True,
                False,
            ),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    70: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "TAGS", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 2,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    71: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "TAGS", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 3,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                True,
                False,
            ),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    72: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "TAGS", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 4,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    73: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "TAGS", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 5,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (
                False,
                False,
                False,
                False,
                False,
                False,
                False,
                True,
                False,
            ),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    74: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "TAGS", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 6,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    75: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "TAGS", "filter_out": False, "__type__": "Terminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 7,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, False, False, False, False, False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    76: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 8,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False, False, False, False, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    77: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 9,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False, False, False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    78: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 10,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False, False, False, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    79: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 11,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False, False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    80: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 12,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False, False, False, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    81: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 13,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False, False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    82: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 14,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False, False, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    83: {
        "origin": {"name": Token("RULE", "actdecl"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "condition", "__type__": "NonTerminal"},
            {"name": "__ANON_1", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 15,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (True, False, False, False, True, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    84: {
        "origin": {"name": Token("RULE", "condition"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "var", "__type__": "NonTerminal"},
            {"name": "CMP", "filter_out": False, "__type__": "Terminal"},
            {"name": "var", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": "condition_long",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    85: {
        "origin": {"name": Token("RULE", "condition"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "var", "__type__": "NonTerminal"},
            {"name": "CMP", "filter_out": False, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": "condition_long",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    86: {
        "origin": {"name": Token("RULE", "condition"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "CMP", "filter_out": False, "__type__": "Terminal"},
            {"name": "var", "__type__": "NonTerminal"},
        ],
        "order": 2,
        "alias": "condition_long",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    87: {
        "origin": {"name": Token("RULE", "condition"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
            {"name": "CMP", "filter_out": False, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 3,
        "alias": "condition_long",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    88: {
        "origin": {"name": Token("RULE", "condition"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "var", "__type__": "NonTerminal"},
            {"name": "UNOP", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 4,
        "alias": "condition_short",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    89: {
        "origin": {"name": Token("RULE", "assignment"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "var", "__type__": "NonTerminal"},
            {"name": "ASSIGN", "filter_out": False, "__type__": "Terminal"},
            {"name": "var", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": "assignment_long",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    90: {
        "origin": {"name": Token("RULE", "assignment"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "var", "__type__": "NonTerminal"},
            {"name": "ASSIGN", "filter_out": False, "__type__": "Terminal"},
            {"name": "INT", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": "assignment_long",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    91: {
        "origin": {"name": Token("RULE", "assignment"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "var", "__type__": "NonTerminal"},
            {"name": "ASSIGN", "filter_out": False, "__type__": "Terminal"},
            {"name": "STAR", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 2,
        "alias": "assignment_long",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    92: {
        "origin": {"name": Token("RULE", "assignment"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "var", "__type__": "NonTerminal"},
            {"name": "UNOP", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 3,
        "alias": "assignment_short",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    93: {
        "origin": {"name": Token("RULE", "var"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "index", "__type__": "NonTerminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "AT", "filter_out": True, "__type__": "Terminal"},
            {"name": "atloc", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    94: {
        "origin": {"name": Token("RULE", "var"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "index", "__type__": "NonTerminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, False, False, False, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    95: {
        "origin": {"name": Token("RULE", "var"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "AT", "filter_out": True, "__type__": "Terminal"},
            {"name": "atloc", "__type__": "NonTerminal"},
        ],
        "order": 2,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True, False, False),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    96: {
        "origin": {"name": Token("RULE", "var"), "__type__": "NonTerminal"},
        "expansion": [{"name": "NAME", "filter_out": False, "__type__": "Terminal"}],
        "order": 3,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    97: {
        "origin": {"name": Token("RULE", "atloc"), "__type__": "NonTerminal"},
        "expansion": [{"name": "AT", "filter_out": False, "__type__": "Terminal"}],
        "order": 0,
        "alias": "at_outer",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    98: {
        "origin": {"name": Token("RULE", "atloc"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "LSQB", "filter_out": True, "__type__": "Terminal"},
            {"name": "index", "__type__": "NonTerminal"},
            {"name": "RSQB", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": "at_inner",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    99: {
        "origin": {"name": Token("RULE", "atloc"), "__type__": "NonTerminal"},
        "expansion": [{"name": "NAME", "filter_out": False, "__type__": "Terminal"}],
        "order": 2,
        "alias": "at_inner",
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    100: {
        "origin": {"name": Token("RULE", "index"), "__type__": "NonTerminal"},
        "expansion": [{"name": "NAT", "filter_out": False, "__type__": "Terminal"}],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    101: {
        "origin": {"name": Token("RULE", "index"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "BINOP", "filter_out": False, "__type__": "Terminal"},
            {"name": "NAT", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    102: {
        "origin": {"name": Token("RULE", "index"), "__type__": "NonTerminal"},
        "expansion": [{"name": "NAME", "filter_out": False, "__type__": "Terminal"}],
        "order": 2,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (False, True, True),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    103: {
        "origin": {"name": Token("RULE", "quantifier"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "FOR", "filter_out": True, "__type__": "Terminal"},
            {"name": "QUANTI", "filter_out": False, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "__quantifier_star_8", "__type__": "NonTerminal"},
            {"name": "__quantifier_star_9", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    104: {
        "origin": {"name": Token("RULE", "quantifier"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "FOR", "filter_out": True, "__type__": "Terminal"},
            {"name": "QUANTI", "filter_out": False, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "__quantifier_star_8", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    105: {
        "origin": {"name": Token("RULE", "quantifier"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "FOR", "filter_out": True, "__type__": "Terminal"},
            {"name": "QUANTI", "filter_out": False, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
            {"name": "__quantifier_star_9", "__type__": "NonTerminal"},
        ],
        "order": 2,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    106: {
        "origin": {"name": Token("RULE", "quantifier"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "FOR", "filter_out": True, "__type__": "Terminal"},
            {"name": "QUANTI", "filter_out": False, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 3,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    107: {
        "origin": {"name": Token("RULE", "start"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__start_star_10", "__type__": "NonTerminal"},
            {"name": "__constraints_plus_3", "__type__": "NonTerminal"},
            {"name": "__start_star_10", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    108: {
        "origin": {"name": Token("RULE", "start"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__start_star_10", "__type__": "NonTerminal"},
            {"name": "__constraints_plus_3", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    109: {
        "origin": {"name": Token("RULE", "start"), "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__constraints_plus_3", "__type__": "NonTerminal"},
            {"name": "__start_star_10", "__type__": "NonTerminal"},
        ],
        "order": 2,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    110: {
        "origin": {"name": Token("RULE", "start"), "__type__": "NonTerminal"},
        "expansion": [{"name": "__constraints_plus_3", "__type__": "NonTerminal"}],
        "order": 3,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    111: {
        "origin": {"name": "__model_star_1", "__type__": "NonTerminal"},
        "expansion": [{"name": "location", "__type__": "NonTerminal"}],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    112: {
        "origin": {"name": "__model_star_1", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__model_star_1", "__type__": "NonTerminal"},
            {"name": "location", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    113: {
        "origin": {"name": "__variables_plus_2", "__type__": "NonTerminal"},
        "expansion": [{"name": "vardecl", "__type__": "NonTerminal"}],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    114: {
        "origin": {"name": "__variables_plus_2", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__variables_plus_2", "__type__": "NonTerminal"},
            {"name": "vardecl", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    115: {
        "origin": {"name": "__constraints_plus_3", "__type__": "NonTerminal"},
        "expansion": [{"name": "actdecl", "__type__": "NonTerminal"}],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    116: {
        "origin": {"name": "__constraints_plus_3", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__constraints_plus_3", "__type__": "NonTerminal"},
            {"name": "actdecl", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    117: {
        "origin": {"name": "__init_star_4", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "simple_init", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    118: {
        "origin": {"name": "__init_star_4", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__init_star_4", "__type__": "NonTerminal"},
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "simple_init", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    119: {
        "origin": {"name": "__simple_init_star_5", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "VBAR", "filter_out": True, "__type__": "Terminal"},
            {"name": "simple_init", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    120: {
        "origin": {"name": "__simple_init_star_5", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__simple_init_star_5", "__type__": "NonTerminal"},
            {"name": "VBAR", "filter_out": True, "__type__": "Terminal"},
            {"name": "simple_init", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    121: {
        "origin": {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    122: {
        "origin": {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__actdecl_star_6", "__type__": "NonTerminal"},
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "condition", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    123: {
        "origin": {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    124: {
        "origin": {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__actdecl_star_7", "__type__": "NonTerminal"},
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "assignment", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    125: {
        "origin": {"name": "__quantifier_star_8", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    126: {
        "origin": {"name": "__quantifier_star_8", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__quantifier_star_8", "__type__": "NonTerminal"},
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "NAME", "filter_out": False, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    127: {
        "origin": {"name": "__quantifier_star_9", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
        ],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    128: {
        "origin": {"name": "__quantifier_star_9", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__quantifier_star_9", "__type__": "NonTerminal"},
            {"name": "COMMA", "filter_out": True, "__type__": "Terminal"},
            {"name": "quantifier", "__type__": "NonTerminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    129: {
        "origin": {"name": "__start_star_10", "__type__": "NonTerminal"},
        "expansion": [{"name": "_NL", "filter_out": True, "__type__": "Terminal"}],
        "order": 0,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
    130: {
        "origin": {"name": "__start_star_10", "__type__": "NonTerminal"},
        "expansion": [
            {"name": "__start_star_10", "__type__": "NonTerminal"},
            {"name": "_NL", "filter_out": True, "__type__": "Terminal"},
        ],
        "order": 1,
        "alias": None,
        "options": {
            "keep_all_tokens": False,
            "expand1": False,
            "priority": None,
            "template_source": None,
            "empty_indices": (),
            "__type__": "RuleOptions",
        },
        "__type__": "Rule",
    },
}
Shift = 0
Reduce = 1


def Lark_StandAlone(**kwargs):
    return Lark._load_from_dict(DATA, MEMO, **kwargs)
